project:
  type: website

website:
  title: "porter"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Medical School
        menu:
          - text: Home
            href: med/home.qmd
          - text: Shadowing
            href: med/shadowing.qmd
          - text: Service
            href: med/service.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

