---
title: "SABER 2023"
---

## When Students Miss class Due to a Medical Condition, Are They Engaging More with Science?

Welcome to the website for our poster! It is here we will go through some of the traditional aspects of a poster, including the "Introduction", "Methods", "Results", and "Conclusion". If you have any questions, please do not hesitate to reach out to Porter at [portergbischoff\@gmail.com](mailto:portergbischoff@gmail.com){.email} !

### Abstract

Prior research has investigated the recruitment and retention of certain student identities (such as gender and ethnicity) in STEM courses and careers. Success in STEM can be influenced by a student's connection to the STEM community, science identity, and engagement. Despite this, no research has investigated the impact of having either a medical experience or chronic condition on STEM students despite research indicating medical students with medical conditions are less likely to complete their degree. Additionally, individuals with medical conditions tend to feel disconnected from others and experience higher levels of stress during their life. Thus, it is important to study the potential impacts of medical experiences and conditions on undergraduate students' STEM motivation.

This study explores the potential impact of having a medical experience or chronic condition for students taking science classes at an open enrollment institution. Specifically, we hypothesized that an increase in academic interruptions due to a medical experience would result in decreased science motivation, a lower sense of belonging, self-efficacy, and self-determination. Pre- and post-course data were collected from 390 students across 14 biology courses (including non-majors) at a teaching-focused institution. Surprisingly, 57% of students surveyed reported having a medical experience and 22% reported having a chronic condition, indicating these are indeed an important and large identity to investigate further.

As predicted, students who have more medical interruptions have a significantly lower sense of belonging and self-efficacy (small effect size). Interestingly, students who indicated that they have had medical experiences and as a result, more engagement with science, have significantly higher science immersion and motivation. Therefore, medical experiences could be influencing student engagement with science in both positive and negative ways. The more interruptions to a student's academics, the more impact it can have on their sense of belonging and self-efficacy. However, if those medical experiences result in more engagement with science, students may be more motivated to understand those experiences in the context of science. Information on the impact medical experiences can have on students is crucial to investigate as science instructors modify course content and pedagogy to be more inclusive of all identities present in the student population.

### Author Information

Porter Bischoff\*, Kody Garrett, Clayton Rawson, Joshua Premo, Brittney N. Wyatt

Department of Biology, Utah Valley University, Orem, UT, 84058, USA.

\*Corresponding author: [portergbischoff\@gmail.com](mailto:portergbischoff@gmail.com){.email}

Acknowledgements: URSCA grant, NSF grant

Conflicts of Interest: The authors have no conflicts of interest to declare.
