---
title: "Introduction"
---
# SABER

<div class="submenu">
  <a href="rproj/2023_saber/home.qmd">About</a>
  <a href="rproj/2023_saber/intro.qmd">Introduction</a>
  <a href="rproj/2023_saber/methods/methods.qmd">Methods</a>
  <a href="rproj/2023_saber/results.qmd">Results</a>
  <a href="rproj/2023_saber/conclusion.qmd">Conclusion</a>
</div>

## Background

Experiences in the classrooms can lead to an increase of STEM motivation. This can come through many different aspects of the classroom experience. One [study](https://onlinelibrary.wiley.com/doi/10.1002/tea.21623) explored the positive impact that performing science practices (like hypothesizing or explaining results) can increase a students' "felt recognition" and "classroom climate", and these two factors increases students' STEM motivation, STEM identity, and STEM career aspirations. Another [study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4657866/) shares that an "intervention emphasizing communal utility value of biomedical research" can greatly increase a students' motivation for biomedical sciences. The study also compared "self-oriented" versus "other-oriented" utility values, showing that "other-oriented" unity values shows a higher student motivation.

Personal experiences can also have a large influence on one's STEM motivation. A [study](https://onlinelibrary.wiley.com/doi/abs/10.1046/j.1365-2923.1999.00293.x) explored a cohort of medical students in Norway and their motivation to go into medicine. Though this is not necessarily "STEM" motivation, the comparison of medicine to STEM fields is important to note. This study went through different life experiences that the students had and compared those back to motivation for different fields in medicine. This was done through a survey, and they asked questions like "opportunity to perform research", opportunity to care for people", or "interest in relations between health, well-being and society". All of these are based on experiences that students might have had on in the past in their lives, and findings show that these experiences can have a significant impact on the paths medical doctors choose. Another [study](https://link.springer.com/article/10.1007/s10648-022-09700-6) explores literature regarding Black and Latinx students' STEM motivation. In this literature review, it is clear that the life experiences that these student have can have a significant impact on their STEM motivation, compared back to experiences of the whole student population.

Personal experiences with medicine can influence career choice. A [study](https://pubmed.ncbi.nlm.nih.gov/25544332/) explores the literature out there regarding how experiences in surgery can have an impact on their career choice. Particularly, much of the literature explores the role that rotations in medical school can influence career choice. This study makes it clear that the experiences people have with medicine can significantly impact what they choose to become. Another [study](https://www.tandfonline.com/doi/abs/10.3109/0142159X.2013.769673) explores the reasons students choose to go into medicine. Many of the common answers included "intellectual curiosity, professional autonomy, altruism, and interest in human relationships". However, in this study, it was clear that students motivated by personal illness or family member's illness "revealed significant\[ly\] greater emotional exhaustion". This makes it clear that our experiences in life can influence our decision to go into medicine.

Chronic illnesses and medical experiences can potentially lead to more interruptions. One [study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9408520/) explores the connection between chronic illness and suicidal ideation in adults in South Korea. What they found was that people with chronic illnesses need attention given to them in order to decrease suicidal ideation. Where suicide is tied to depression, the connection between having a chronic condition and potentially missing class becomes clear, as the students could miss more class due to the increase in depression. Another [study](https://link.springer.com/article/10.1007/s15010-015-0801-y) explores how having chronic illnesses increase the incidence of pneumococcal pneumonia in older adults. In particular, it goes into what specific illnesses could cause an increase in incidence of pneumonia. Comparing this back to our study, students with chronic conditions could miss more classes due to illnesses (like pneumonia). Lastly, another [study](https://link.springer.com/article/10.1007/BF02088595) shows the influence that chronic illnesses (especially diabetes and psychiatric conditions) have on a person's self-esteem. If a student has lower self-esteem, they may feel less likely to attend class, and therefore, these chronic conditions can lead to more medical interruptions.

## Motivation for the Project

Porter has had a slew of medical experiences, and these experiences led him to pursue a career path in medicine. While going through his undergraduate experience, preparing for medical school, he found a real passion for science as well as medicine. Because this was relatively late in his education, he wishes that he knew this passion he had before his undergraduate studies. Therefore, this project was born, hoping to find that Porter wasn't uncommon in his experience and assisting other students understand their passions for science sooner than later. To learn more about how this project became to be, [please go to this link!](https://youtu.be/ZyujRGODbs4)
